version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/react/Dockerfile
    volumes:
      - ./next:/usr/src/app/next
    command: yarn dev
    ports:
      - "3000:3000"
